### PR TITLE
New Feature: Default TTL

### PR DESCRIPTION
**Pull request by ekristen**
* implements the ability to set a default TTL for all keys
* adds appropriate tests
* removes the use of spaces to prevent looping problems with the default ttl feature
* adds additional namespacing (!x!) to expiration keys and more defined range query

Thanks to @ralphtheninja for the help and inspiration.

/cc @ralphtheninja @hij1nx

### CODE REVIEW

**Comment by ekristen** [comment]
New refactored PR to replace https://github.com/rvagg/node-level-ttl/pull/20 (which I already closed)

**Comment by ralphtheninja** [comment]
:+1:

**Comment by rvagg** [comment]
leave this open for a bit to get further comment and then one of the collaborators can merge it if there's no objections, unfortunately I don't have the headspace to get in to this so I'll trust the others to review

**Comment by hij1nx** [comment]
:+1:

**Comment by ralphtheninja** [comment]
I'll merge this on Monday and get a new release out. I'm thinking we should bump the version to `3.0.0`. Sounds ok?

/cc @rvagg @mcollina @ekristen @hij1nx

**Comment by rvagg** [comment]
Do we have a breaking change to warrant that? I'm fine either way, better to be over-cautious with semver than relaxed about it.

**Comment by ralphtheninja** [comment]
@rvagg Well, it's not a breaking change with the api, but the dependencies have changed quite drastically since we no longer depend on `level-spaces` so I just wanted to be on the "safe" side.

**Comment by rvagg** [comment]
sure, if you'd prefer to be safe then I have no objections, you're release master now so you have to wear the results of these decisions

**Comment by mcollina** [comment]
I'm :-1: against this as it is. If you are not using sublevel this is perfectly fine, but if you are this 'does not do the right thing'. In particular it adds more entries to the current keyspace, and it is a little bit counterintuitive in that sense.

I would make it a little bit more convoluted than this: if there is a `sub` method on the `db`, then create a new sub-sub-level for the metadata. If there is no `sub` method, than prefix the keys like this one does.

Anwyay, :+1: for bumping the major in any case.

**Comment by ralphtheninja** [comment]
@mcollina Currently on master we check `options.sub` I guess that is what you're referring to?

**Comment by mcollina** [comment]
@ralphtheninja yes. That functionality is _very needed_, and if no sub is present we can just switch to the key prefix thing.

**Comment by ekristen** [comment]
@mcollina I am a little confused by your comments, if you could elaborate more I'd really appreciate it. I would like to answer your question as best as possible. In the mean time I'll take a stab at why level-sublevel is a problem. Especially your comments of "does not do the right thing" and "adds more keys to the current keyspace".

The problem with using `db.sub` is that `db.sub.put`s and `db.sub.batch` method doesn't get the override like `db.put` and `db.batch` does by `level-ttl` which can lead to some odd behavior (like loops) when it comes to adding keys with the ttl option.   My original PR https://github.com/rvagg/node-level-ttl/pull/20 attempted to solve this by adding this https://github.com/rvagg/node-level-ttl/pull/20/files#r23281386 which wasn't a very nice fix, especially if the separator being used for the key was different.

Is there a specific reason why level-ttl needs to support sublevels? With this PR it adds the separator option and so you can control the key prefix entirely if you do not like the default?

**Comment by mcollina** [comment]
Here is the problem your thing does not solve:

1. User write 3 key/value pair with TTLs.
2. User create a readstream over the whole repo, and it gets 6 keys, not 3.

In current master (and previous versions), the readstream would return 3.

I am perfectly fine with level-ttl non supporting sublevel, but it is _the_ feature that got me into this project at the very beginning. Also on LevelUp, like composing bricks and so on. I think we are losing functionality in here.

**Comment by ralphtheninja** [comment]
@mcollina 

So your main concern is the support for a sublevel to store the meta data separately? If that's the case, I totally agree. It should be possible to keep that data by itself.

However, that sublevel would still have to be a separate db, right? Since producing a readstream over the whole db would still produce a stream of all keys (unless the data is also stored in a separate sublevel and you stream that separately).

Could you provide a short code snippet for how you are using it or would like to use it. I think that would help a great deal with understanding your use case. Sorry for being a pain :)

**Comment by ekristen** [comment]
@mcollina Are you wanting the ability to use `level-ttl` on a `level-sublevel`?

**Comment by mcollina** [comment]
level-ttl was working fine over sublevel back in the days, with the exact behavior I explained above. I want to maintain my keys in two different sublevels, so the reading a range from the first will not show the sublevel keys. Basically, as it is now on master and I do not see any points in changing that behavior.

Unfortunately I am in a hurry these days with very few time to spend on this :(.

**Comment by ralphtheninja** [comment]
@mcollina We're on the same page here and no one wants to change the current behavior. I just want to make sure that I understand your use case. This will be purdy, don't worry :)

**Comment by ekristen** [comment]
@mcollina AFAICT the latest version of `level-ttl` doesn't work with `sublevels` so are you making the case that it should support level-sublevels? I've just read up on your issue https://github.com/rvagg/node-level-ttl/issues/15 and @rvagg comments. 

This PR doesn't change any of the current behavior, but does not make level-ttl compatible with sublevels.

**Comment by mcollina** [comment]
@ekristen this commit makes it working on level-sublevel https://github.com/rvagg/node-level-ttl/commit/c0c81191bcaefba1770850d6cd78feea16dcaa6f.

**Comment by ekristen** [comment]
@mcollina I am following you now. Let me think about this a bit.

**Comment by ralphtheninja** [comment]
Aye, so if `options.sub` is set, use that to store the meta data (instead of batching all to provided db), otherwise fallback to current code.

**Comment by ralphtheninja** [comment]
@mcollina Would this snippet summarize what you need?

```js
var level = require('level');
var ttl = require('level-ttl');
var sublevel = require('level-sublevel');
var db = sublevel(level('./testdb'));
 
ttl(db.sublevel('keys'), { sub: db.sublevel('meta') })
```

**Comment by mcollina** [comment]
@ralphtheninja yes, thanks! :)

**Comment by ralphtheninja** [comment]
I hacked up a gist [`here`](https://gist.github.com/ralphtheninja/69dde0ca7e1fe86a6fd8) to illustrate further. We have two sublevels, one for the data and one for the meta and we can use `createReadStream()` on different parts to get either data, meta or everything.

I think it could be wise to continue using `db._ttl.sub` like before. It would make the code transparent to what is being used for the meta data and a lot less convoluted.

**Pull request closed without merging**
