### PR TITLE
New Feature: Default TTL

### PR DESCRIPTION
**Pull request by ekristen**
This is an alternative implementation to https://github.com/rvagg/node-level-ttl/pull/25 that removes level spaces, and uses sublevels entirely. All tests pass.

@mcollina @hij1nx @ralphtheninja

### CODE REVIEW

**Comment by ArtskydJ** [comment]
Does it work to pass in a level-spaces database?

**Comment by ekristen** [comment]
No. Unfortunately the way that `level-spaces` operates in comparison to `level-sublevel` it won't work. The problem is the `level-ttl` overrides the default `put` and `batch` methods of `levelup` and `level-sublevel` makes proper use of `level-ttl`.

Unfortunately `level-spaces` instantiates `levelup` so its method's do not get override which causes problems with recursive loops with certain ttl operations to include `default_ttl` feature.

**Comment by ralphtheninja** [comment]
@ekristen Would you mind squashing these commits and force push your feature branch? Some of the changes in the second commit are essentially undoing changes in the first so it would be a lot easier to see what has changed from current master.

**Comment by ekristen** [comment]
@ralphtheninja done. The tests failed, but I think that is just because of slow CPU/Disk on Travis, if you can as a contributor rerun https://travis-ci.org/rvagg/node-level-ttl/builds/51171739, it should pass no problem.

**Comment by TehShrike** [comment]
I had to re-run the test twice to get a pass.

**Comment by ekristen** [comment]
The tests are valid and pass. It's a CPU and disk speed issue that cause a random ones to fail

**Comment by ralphtheninja** [comment]
@mcollina Mind having a quick look? This seems to work fine with `level-sublevel`.

**Comment by mcollina** [comment]
This is much more in the line on which level-ttl used to work. However, I was suggesting not to force a dependency on sublevel using the method in https://github.com/rvagg/node-level-ttl/pull/25 if no 'sub' is given. Does it make any sense? Could these two be merged?

**Comment by ralphtheninja** [comment]
@mcollina Aah ok. Yes it makes sense. I just thought it would be easier to depend on it and would make the code less convoluted. Let me try something and get back to you.

**Comment by ralphtheninja** [comment]
@mcollina What do you think about this?

**Comment by ralphtheninja** [comment]
On a side note. If we are going to change major version, we might as well remove backwards compatibility for `options.sublevel`?

https://github.com/rvagg/node-level-ttl/blob/8010e39885265957ad1ba4df7a50a6f634d7255c/level-ttl.js#L222-L224

@rvagg Sound ok?

**Comment by mcollina** [comment]
Does it also works with level-spaces? In any case, ok for me.

**Comment by ralphtheninja** [comment]
@mcollina Good question. Let me try.

**Comment by rvagg** [comment]
Sorry, zero mental bandwidth to absorb this. Do your best and I'll just have to catch up later and adapt if need be. Thanks @ralphtheninja!

**Comment by ralphtheninja** [comment]
@mcollina Seems to work fine with `level-spaces` as well

```js
var crypto = require('crypto')
var level = require('level')
var spaces = require('level-spaces')
var ttl = require('level-ttl')
var path = __dirname + '/ttldb'

level(path, function (err, db) {
  if (err) throw err
  var ttldb = ttl(db, { sub: spaces(db, 'spaaaaace-yeaaaaaaah') })
  ttldb.batch(randomBatch(3), { ttl: 10000 }, function (err) {
    if (err) throw err
    ttldb.createReadStream()
      .on('data', function (data) {
        console.log('%s / %s', data.key, data.value)
      })
  })
})

function randomBatch(count) {
  var batch = []
  for (var i = 0; i < count; ++i) {
    var key = crypto.randomBytes(32).toString('base64')
    var value = crypto.randomBytes(32).toString('base64')
    batch.push({ type: 'put', key: key, value: value })
  }
  return batch
}
```

```
$ node ttl-spaces.js 
CTtYI8PGehlnPVlY6CThTQe8pebp901wKWP/gb+7NuY= / fFGRO7wDQoyp6LxlqeebV8ZshuUxJzbw79/ZG8Vw9fA=
a9RHjkQGYUUIBhQRXuHUNtQZQapF4VP2nNj3wsriyCQ= / WpNcREh2UEwVotk/K8jCwMdwwgmq3mZkZYOwglT5Bcw=
mj5pb0K+ixeE+a5n4g9z3ryOF+YJdF4u/pXfUy8tX4o= / INbj73F7vGFa+DciOv5qapNMIMq4GMPpE9NHu0CPDk4=
~spaaaaace-yeaaaaaaah~CTtYI8PGehlnPVlY6CThTQe8pebp901wKWP/gb+7NuY= / 1424561851960
~spaaaaace-yeaaaaaaah~a9RHjkQGYUUIBhQRXuHUNtQZQapF4VP2nNj3wsriyCQ= / 1424561851960
~spaaaaace-yeaaaaaaah~mj5pb0K+ixeE+a5n4g9z3ryOF+YJdF4u/pXfUy8tX4o= / 1424561851960
~spaaaaace-yeaaaaaaah~x!1424561851960!CTtYI8PGehlnPVlY6CThTQe8pebp901wKWP/gb+7NuY= / CTtYI8PGehlnPVlY6CThTQe8pebp901wKWP/gb+7NuY=
~spaaaaace-yeaaaaaaah~x!1424561851960!a9RHjkQGYUUIBhQRXuHUNtQZQapF4VP2nNj3wsriyCQ= / a9RHjkQGYUUIBhQRXuHUNtQZQapF4VP2nNj3wsriyCQ=
~spaaaaace-yeaaaaaaah~x!1424561851960!mj5pb0K+ixeE+a5n4g9z3ryOF+YJdF4u/pXfUy8tX4o= / mj5pb0K+ixeE+a5n4g9z3ryOF+YJdF4u/pXfUy8tX4o=
```

**Comment by ralphtheninja** [comment]
@ArtskydJ Now it does.

If people are happy with this I'll squash the commits before merge.

**Comment by ralphtheninja** [comment]
On second thought this is not compatible with `level-spaces`, at least not if you're using defaultTTL.

**Comment by ralphtheninja** [comment]
```
$ npm publish
+ level-ttl@3.0.0
```

**Comment by mcollina** [comment]
I would a little note for level-subspaces compatibility, telling people that the module is partially compatible with it (but not for defaultTTL).

**Comment by ralphtheninja** [comment]
@mcollina Good point! I assume you meant `level-spaces` :)

**Pull request merged**
